language: node_js
node_js: node
sudo: required
before_install: if [ "${TRAVIS_MODE}" != "funcTests" ]; then unset SAUCE_USERNAME
  && unset SAUCE_ACCESS_KEY; fi
script: "./scripts/travis.sh"
stages:
- buildAndTest
- releaseAlpha
- release
- testFuncRequired
- testFuncOptional
jobs:
  fast_finish: true
  allow_failures:
  - stage: testFuncOptional
  include:
  - stage: release
    if: tag IS present
    env: TRAVIS_MODE=release
    deploy:
      provider: releases
      api_key:
        secure: kR9xHKhWfOv6vwxz1d//PpC22VDupnPI59L9czLkpLoIdzm5rm3eV7he4XPlQfbSrV1UBgURARgF+yekmeqUZk9vqfo4F5oa+6KiBxAdnI9PjsjYRSXitdq4a6kpIR854nxUIOlDXR5AbD2MgNaKsQHiaNlngdR/870OhiwqRJVwQOLKVUADw1QWECXe/DXrQiFbMunxBrTyutbrGuI8cT7wzqFn+aPkI/3liiw8PTr93GrtxZ/bFxI899KzMSHHMXB+eDDMtxPFD+VApruD7h6f+1C0psJeOV8/PkzrRkbPELPBKKaPH9TvVOPUf2OSRHVna828wnLHwseae0rgtuk7+ZJmB9XZKX9FUBDT4/Gv/AkE+m/cwnoqaatAMJYR+yiQqsosjBLDAaTUOPHu3wBdAaR5uL5fGsSsKe3sUfSQHrv86vReNl9ETU06apmyWtsIbyhMtv98j9I+hNVjKZUI30g1ee6LgjlDlBavMk8KAbLbyBTcJlNAexj8Rppdqg+AdW7rYW+S6SgfTyyYQKTLeFwmDjfrkqzHJnk78sV18+xPLI1hbzBGp/bXaW23sLDBLLV5Sxifr8flUMkUdH28zsLCHUQ7C4GKQ19el2NZgIxSsnxRA8vGZof7OXasR4HJVjv/PSx+DN6Fi1PV1SiNBcwgPCGIIxBF7TUPxJk=
      file_glob: true
      file: dist/*.{js,js.map}
      draft: true
      tag_name: "$TRAVIS_TAG"
      target_commitish: "$TRAVIS_COMMIT"
      skip_cleanup: true
      on:
        tags: true
  - stage: releaseAlpha
    if: branch = master AND type != pull_request
    env: TRAVIS_MODE=releaseAlpha
  - stage: buildAndTest
    env: TRAVIS_MODE=build
  - stage: buildAndTest
    env: TRAVIS_MODE=unitTests
  - stage: testFuncRequired
    env: TRAVIS_MODE=funcTests UA=chrome              OS="Windows 10"
  - stage: testFuncOptional
    env: TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.15"
  - stage: testFuncOptional
    env: TRAVIS_MODE=funcTests UA=firefox             OS="Windows 10"
  - stage: testFuncOptional
    env: TRAVIS_MODE=funcTests UA=chrome              OS="OS X 10.11"  UA_VERSION="79.0"
  - stage: testFuncOptional
    env: TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 10"
  - stage: testFuncOptional
    env: TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 8.1" UA_VERSION="11.0"
  - stage: testFuncOptional
    env: TRAVIS_MODE=funcTests UA=chrome              OS="Windows 7"   UA_VERSION="69.0"
  - stage: testFuncOptional
    env: TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.12"  UA_VERSION="10.1"
addons:
  sauce_connect:
    tunnel_domains: localhost
env:
  global:
    secure: i7im+yazBs83ioDWQvE7jD7gKnB7kL8ZQIAXV3OpcM9uByguQ71HjS8r/Ywjb03ntOsHNncrCDcE1gRn6PlinSsq1UsWnnW8bCiQA2UgWeWSOYpq43I/8gK43jMShdSdO8UoI94bbdPDtKOy+c5MnuMDjYmgSxVlonOXrACC1CHfwvLoS6lY8YMQDeOPbrg8bgDYdgr1k4EOjk9dIxa+DOjlNJCi4KrkJ1szntZNL/1FWc6GGAgXl22gyXHTt7q7KvhTXrYqnnrghNHS43TiG6ZIFIOKqcnqA/2WDKov13UPrXBVtJKv6Nbkw3bxaB5Hp5+Qv+jVKkTxJ8l0BT8xk/h71qtbr+frHxHaKbvdJJCKJq9SXiPK3sAXtzIL+d46cJzI9+cqitqeE8c9p+D8A8Zj+DdcwI9Ff5roz6yUisFxnz07BNKy7u8OKzKF1/zwSC21U8Q+PERkq3e6WsC+BKMUVBk/yCa3MUYD26DCQSmeAe9EGb8H1b9wE2PmkosHZXCrLrfhXDsho1uHBzhcO3nRN4TSleJfQpbJgaMUo1R9KNR75TK5n/EVBSXCpxmC/AyluIUTu/vjYYeEW+F/Jzbk9UwrCIfn4b6LBiZoG3PohgkJVnT0YN0CAeWAojjsHW91x2CAdkCKPJNS27ysdvlAg/0txkaxArAsqZn3wSw=
